#!/bin/sh
sudo apt install libxcb-xkb-dev libpam0g-dev
cd ~/Downloads
git clone https://github.com/fairyglade/ly/archive/refs/tags/v0.6.0.tar.gz
cd ly
make && sudo make install installsystemd
sudo systemctl enable ly
