#!/bin/sh
mkdir -p ~/Downloads/cascadia-code
cd ~/Downloads/cascadia-code
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.tar.xz
tar -xf CascadiaCode.tar.xz
rm -rf CascadiaCode.tar.xz
cd ..
sudo cp -r cascadia-code /usr/share/fonts/truetype
fc-cache
